AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
