#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))
require "jw_calendar"
require "jw_calendar/cli/runner"

exit JWCalendar::CLI::Runner.new.run(ARGV)
